config/routes.rb
Rails.application.routes.draw do
  root to: 'users#toppage'
  resources :users 

  resources :favorites, only: [:create, :destroy, :index]

  resources :sessions, only: %w!new create destroy!
  
  resources :pictures do 
    collection do 
      post :confirm
      get :user_favorites
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }  
  
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  has_many :pictures
  has_secure_password
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def show
    @picture = picture.find(params[:id])
    @favorites = favorite.where(picture_id: @picture.id).all
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
    if current_user.id != @picture.user_id
      redirect_to pictures_path, notice: 'あなたの投稿ではありません。'
    end
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = current_user.pictures.build(picture_params)
    respond_to do |format|
      if params[:back]
        format.html { render :new }
      else
        if @picture.save
          ContactMailer.contact_mailer(@picture).deliver
          format.html { redirect_to @picture, notice: '投稿しました' } 
          format.json { render :show, status: :created, location: @picture }
        else
          format.html { render :new }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def confirm
    @picture = current_user.pictures.build(picture_params)
    render :new if @picture.invalid?
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
          format.html { redirect_to @picture, notice: '投稿を編集しました' }
          format.json { render :show, status: :ok, location: @picture }
        else
          format.html { render :edit }
          format.json { render json: @picture.errors, status: :unprocessable_entity }
        end
      end
    end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: '投稿を削除しました' }
      format.json { head :no_content }
    end
  end

  def user_favorites
    @favorites = current_user.favorite_pictures
  end

  private
  def set_picture
    @picture = Picture.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)

    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    if current_user.id != @user.id
      redirect_to root_path, notice: 'あなたのアカウントではありません。'
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: 'ユーザーを作成しました。さっそくログインしてみよう！' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報を更新しました' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'ユーザーを削除しました' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_pictures_path
    else
      action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTask3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">Bootstrap</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Instagram Clone</a>
          </div>

          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <% if logged_in? %>
                <li><%= link_to "#{current_user.name}さんのマイページ", user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
                <li><%= link_to "投稿する", new_picture_path %></li>
                <li><%= link_to "投稿一覧", pictures_path %></li>
                <li><%= link_to "お気に入り", user_favorites_pictures_path %></li>
              <% else %>
                <li><%= link_to "トップページ", root_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
                <li><%= link_to "新規登録", new_user_path %></li>
              <% end %>
              
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% flash.each do |key,value| %>
      <%= content_tag(:div,value,class:"#{key}") %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
    <th><%= form.label :title %></th>
    <td><%= form.text_field :title, size: "25*25" %></td>
    </tr>


    <tr>
    <th><%= form.label :content %></th>
    <td><%= form.text_field :content, size: "25*25" %></td>
    </tr>

    <tr>
    <th><%= form.label :image %></th>
    <td><%= form.file_field :image %></td>
    <th><%= form.hidden_field :image_cache %></th>
    <th><%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></th>
    </tr>
  </table>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で送信します。</h3>

<%= form_with(model: @picture, local: true, url: pictures_path) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :image_cache %>

  <p>Title：<%= @picture.content %></p>
  <p>Content：<%= @picture.content %></p>

  <% if @picture.image? %>
    <%= image_tag @picture.image.url, size: '410x300' %>
  <% end %>

  <br>
  <br>
  <%= form.submit "作成する", class: 'btn btn-success'%>
  <%= form.submit "戻る", name: 'back', class: 'btn btn-warning' %>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>投稿一覧</h1>
<br>

<tbody>
  <% @pictures.each do |picture| %>
  <br>
    <h2 class="index_title">タイトル：<%= picture.title %></h2>
    <br>
    <div class=index_main>
      <% if picture.image? %>
        <%= image_tag picture.image.url, :size =>'410x300' %>
        <% else %>
        <%= image_tag "Noimage_image.png", :size =>'410x300' %>
      <% end %>
      
      <br>    
      <h3>一言：<%= picture.content %></h3>
      <br>
      <h4>投稿者：<%= link_to picture.user.name, user_path(picture.user.id) %></h4>
      <%= link_to '詳細を見る', picture %>
      <% if current_user.id == picture.user_id %>
        <%= link_to '編集する', edit_picture_path(picture) %>
        <%= link_to '削除する', picture, method: :delete, data: { confirm: '本当に削除しますか?' } %>
      <% end %>
      <br>
      <br>
    </div>    
  <% end %>
</tbody>

<br>
<%= link_to '投稿する', new_picture_path, class: 'btn btn-info' %>

app/views/pictures/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', picture: @picture %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @picture.content %>
</p>

<% if @picture.image? %>
  <%= image_tag @picture.image.url, size: '410x300' %>
<% end %>
<br><br>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<br>

<%= link_to '編集', edit_picture_path(@picture), class: "btn btn-info" %> |
<%= link_to '投稿一覧へ', pictures_path, class: "btn btn-warning" %> 

app/views/pictures/user_favorites.html.erb
<h2><%= current_user.name %>さんのお気に入り投稿</h2>

<br>
<h1>--------------------------------</h1>
<% @favorites.each do |favorite| %>
  <h3>投稿者：<%= favorite.user.name %></h3>
    <h3>タイトル：<%= favorite.title %></h3>
    <h3>一言：<%= favorite.content %></h3>

    <% if favorite.image? %>
      <%= image_tag favorite.image.url %>
    <% end %>
    <h1>--------------------------------</h1>
  <% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="errors">
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <ul class="field">
    <li><%= form.label :name %></li>
    <li><%= form.text_field :name %></li>
  </ul>

  <ul class="field">
    <li><%= form.label :email %></li>
    <li><%= form.text_field :email %></li>
  </ul>

  <ul class="field">
    <li><%= form.label :password %></li>
    <li><%= form.password_field :password %></li>
  </ul>

  <ul class="field">
    <li><%= form.label :password_confirmation %></li>
    <li><%= form.password_field :password_confirmation %></li>
  </ul>

  <ul class="field">
    <li><%= form.file_field :image %></li>
  </ul>
    
  
  
  


  <ul class="actions">
    <li><%= form.submit %></li>
  </ul>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>ユーザー情報の編集</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', @user, class: "btn btn-info" %> 

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <% if current_user.id != @picture.user_id %>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>ユーザを新規作成します</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<h2><%= @user.name %>さんのマイページ</h2>

<p>
  <strong>名前:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>メールアドレス:</strong>
  <%= @user.email %>
</p>

<% if @user.image? %>
  <%= image_tag @user.image.url %>
<% end %>
<br>
<br>

<% if current_user.id == @user.id %>
  <%= link_to '設定変更', edit_user_path(@user), class: 'btn btn-success' %> |
<% end %>
  <%= link_to '投稿一覧へ', pictures_path, class: 'btn btn-warning' %> 


      

app/views/users/toppage.html.erb
<div class="toppage">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 toppage_center">
      <h2><%= link_to "ログイン", new_session_path, class: 'btn btn-info login_btn'%></h2>
      <br>
      <h4><%= link_to "初めての方はこちら", new_user_path, class: 'btn btn-success'%></h4>
    </div>
    <div class="col-md-4 toppage_right">
      <h1></h1>
      <br>
    </div>
  </div>
</div>